name: Process API Data

on:
  schedule:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Confirm Version
      run: go version

    - name: Run
      env:
      run: |
        go build ./cmd/guConverterJobs
        ./guConverterJobs
