name: Update KV

on:  
  push:
  pull_request:
  schedule:
    - cron: '21 * * * *'


jobs:
  # Create all builds for various platforms
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'

    - name: Confirm Version
      run: go version

    - name: Run
      run: |
        go run ./cmd/processMatches/processMatches.go
